server:
  forward-headers-strategy: framework
  tomcat:
    max-http-form-post-size: 10MB

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DB_SCHEMA}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

aes:
  secret-key: ${AES_SECRET_KEY}

hmac:
  secret-key: ${HMAC_SECRET_KEY}

clova:
  ocr:
    secret-key: ${CLOVA_OCR_SECRET_KEY}
    invoke-url: ${CLOVA_OCR_INVOKE_URL}